

ko:
  title: 크리에이터 랜딩 페이지 | Hugo 테마
  languageName: 한국어
  languageCode: ko-kr
  weight: 1

en:
  title: Creator's Landing Page | Hugo Theme
  languageName: English
  languageCode: en-us
  weight: 2

