main:
  - name: Home
    url: /#top
    weight: 10

  - name: About
    url: /#about
    weight: 15

  - name: Core Competencies
    url: /#features
    weight: 20

  - name: Projects
    url: /#project-title
    weight: 30

  - name: Experience
    url: /#experience
    weight: 35

  - name: Project Details
    identifier: project
    weight: 40

  - parent: project
    name: AFF Diagnosis System
    url: 'https://github.com/tunho/aff-diagnosis-system'
    weight: 41

  - parent: project
    name: Knee-Angle Residual Correction
    url: 'https://github.com/tunho/squat-knee-residual-correction'
    weight: 42

  - parent: project
    name: Thyroid Supplement CDSS
    url: 'https://github.com/tunho/thyroid-supplement-cdss'
    weight: 43

  - name: Additional Information
    identifier: resources
    weight: 50

  - parent: resources
    name: My Introduction
    pageRef: '/blog/my-introduce'
    weight: 52

  - parent: resources
    name: Jeonbuk National University
    pageRef: '/blog/jb-uni'
    weight: 53

  - parent: resources
    name: Research Lab Introduction
    pageRef: '/blog/macs-lab'
    weight: 51

footer:
  - name: 'JBNU Junho Lee'
    pageRef: '/jbnu-junho-lee'
    weight: 90
