main:
  - name: 홈
    url: /ko/#top
    weight: 10

  - name: "전북대 이준호"
    pageRef: "/jbnu-junho-lee"
    weight: 12

  - name: 피쳐
    url: /ko/#features
    weight: 20

  - name: 솔루션
    url: /ko/#solutions
    weight: 30

  - name: 리소스
    identifier: resources
    weight: 40

  - parent: resources
    name: 블로그
    pageRef: "/blog"
    weight: 41

footer:
  - name: "전북대 이준호"
    pageRef: "/jbnu-junho-lee"
    weight: 90
