main:
  - name: 홈
    url: /#top
    weight: 10

  - name: 소개
    url: /#about
    weight: 15

  - name: 피쳐
    url: /#features
    weight: 20

  - name: 프로젝트
    url: /#project
    weight: 30

  - name: 리소스
    identifier: resources
    weight: 40

  - parent: resources
    name: 블로그
    pageRef: '/blog'
    weight: 41

  - parent: resources
    name: 상세 소개
    pageRef: '/jbnu-junho-lee'
    weight: 42

footer:
  - name: '전북대 이준호'
    pageRef: '/jbnu-junho-lee'
    weight: 90
