# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/


#홈페이지 대표 이미지 수정
title: "Junho Lee"
description: "JBNU · Medical AI · Full-stack"
social:
  twitter: tunho

  
# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Jeonbuk National University (JBNU) Junho Lee · 전북대 이준호'
    description: '전북대학교 컴퓨터인공지능학부 이준호(준호 이) 개인 포트폴리오 · JBNU · 전북대'
    twitter: 'GetResearchDev'
    image: 'og-default.jpg'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    align: 'center'
    fixed_to_top: true
    logo:
      text: ''                 # 텍스트는 비우고
      filename: 'my-image.jpg'    # ← 여기에 파일명만 지정
      alt: 'Junho Lee'         # (선택) 대체 텍스트
    button:
      enable: false
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} My Company'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'



